### ISSUE TITLE
Mac OS X Exports Empty Folder

### ISSUE THREAD

**Issue by schnaser** [teamprevue/PreVue#88]
On OSX I've created a simple project with the default route and one component. When I click the upper-right Export Project button, I just get an empty folder. Is there something I'm doing wrong or haven't set up properly?

Repro steps:
 - Import the attached project
 - click export ptoject

Expected: Vue project is exported

Actual: Blank folder is exported

[test-project.json.zip](https://github.com/teamprevue/PreVue/files/3023290/test-project.json.zip)

**Comment by danshuu** [comment]
Hi Mike, 

Did you accidentally click save project instead of export project or are you exporting the project as a JSON file? If you click save project button you will save your project as a JSON file so that you can reopen your prototype later, and the exporting project button will export the project code. Try clicking export project and saving the folder name without an extension. Let me know if there are any further issues with this.

- Daniel

**Comment by al2613** [comment]
Hey Mike, 

Thanks for notifying us. We identified the issue and we're working on fixing it plus possible feature enhancements

Thanks!
Annette

**Comment by CodingTanna** [comment]
Same Problem on a Linux Mint 19 Cinnamon.

**Comment by danshuu** [comment]
Hi Mike,

The issue has been fixed! Let us know if there are any other questions or concerns.

Thanks,
Daniel
